name: Build (and release)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published", "edited" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Get the sources
      uses: actions/checkout@v4

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Run Cake script
      uses: cake-build/cake-action@v1
      with:
        verbosity: Diagnostic
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
